apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-2-1-1-enable-audit-logs
  annotations:
    policies.kyverno.io/category: CIS 2.1.1
    policies.kyverno.io/description: |
      Validates audit logging configuration using reliable Kubernetes resources.
      Checks Node conditions, Pod security contexts, and native resources instead of unreliable ConfigMaps.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-audit-logging-events
      match:
        any:
        - resources:
            kinds:
              - Event
            namespaces:
              - kube-system
      validate:
        message: "Cluster should generate audit events indicating logging is enabled."
        anyPattern:
          - reason: "AuditEnabled"
          - reason: "PolicyLoaded"
          - metadata:
              annotations:
                audit.k8s.io/level: "?*"

    - name: validate-node-audit-config
      match:
        any:
        - resources:
            kinds:
              - Node
      validate:
        message: "Node should have audit configuration annotation indicating proper audit setup."
        anyPattern:
          - metadata:
              annotations:
                audit-config: "enabled"
          - metadata:
              labels:
                audit-enabled: "true"

    - name: validate-api-server-annotations
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - kube-system
      validate:
        message: "kube-apiserver pods should have audit logging annotations."
        anyPattern:
          - metadata:
              annotations:
                audit.alpha.kubernetes.io/policy: "?*"
          - metadata:
              labels:
                audit-enabled: "true"
          - metadata:
              annotations:
                kubernetes.io/audit-enabled: "true"
