apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-2-1-1-enable-audit-logs
  annotations:
    policies.kyverno.io/category: CIS 2.1.1
    policies.kyverno.io/description: |
      Checks for audit logging configuration in ConfigMap or node annotations if available.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-audit-logging
      match:
        any:
        - resources:
            kinds:
              - ConfigMap
      validate:
        message: "Audit logging should be enabled (look for 'audit' in data.logging)."
        pattern:
          data:
            logging: "?*audit?*"

    - name: validate-node-audit-config
      match:
        any:
        - resources:
            kinds:
              - Node
      validate:
        message: "Node should have audit configuration annotation indicating proper audit setup."
        anyPattern:
          - metadata:
              annotations:
                audit-config: "enabled"
          - metadata:
              labels:
                audit-enabled: "true"

    - name: validate-eks-audit-logging
      match:
        any:
        - resources:
            kinds:
              - ConfigMap
            names:
              - eks-cluster-config
            namespaces:
              - kyverno-aws
      validate:
        message: "EKS control plane logging must be enabled for audit logs."
        pattern:
          data:
            logging: "*audit*"

    - name: validate-cluster-logging-annotation
      match:
        any:
        - resources:
            kinds:
              - ConfigMap
            names:
              - cluster-logging-config
      validate:
        message: "Cluster logging configuration must indicate audit logging is enabled."
        anyPattern:
          - data:
              audit-enabled: "true"
          - metadata:
              annotations:
                logging.cluster/audit: "enabled" 