# Kyverno CIS Resource Access RBAC Extension
# This extends Kyverno's default RBAC with resource access permissions required for CIS EKS validation

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:system:resource-reader
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/version: v1.13.6
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/managed-by: manual
  annotations:
    rbac.authorization.k8s.io/autoupdate: "true"
    meta.helm.sh/release-name: kyverno
    meta.helm.sh/release-namespace: kyverno
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
  resourceNames: []
- apiGroups: [""]
  resources: ["nodes/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch"]

---
# Bind CIS resource access to kyverno admission controller for policy evaluation
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno:system:resource-reader:admission-controller
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/version: v1.13.6
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/managed-by: manual
  annotations:
    rbac.authorization.k8s.io/autoupdate: "true"
    meta.helm.sh/release-name: kyverno
    meta.helm.sh/release-namespace: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:system:resource-reader
subjects:
- kind: ServiceAccount
  name: kyverno-service-account
  namespace: kyverno

---
# Bind CIS resource access to kyverno reports controller for background scanning
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno:system:resource-reader:reports-controller
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/version: v1.13.6
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/managed-by: manual
  annotations:
    rbac.authorization.k8s.io/autoupdate: "true"
    meta.helm.sh/release-name: kyverno
    meta.helm.sh/release-namespace: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:system:resource-reader
subjects:
- kind: ServiceAccount
  name: kyverno-reports-controller
  namespace: kyverno

---
# Bind CIS resource access to kyverno cleanup controller if needed
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno:system:resource-reader:cleanup-controller
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/version: v1.13.6
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/managed-by: manual
  annotations:
    rbac.authorization.k8s.io/autoupdate: "true"
    meta.helm.sh/release-name: kyverno
    meta.helm.sh/release-namespace: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:system:resource-reader
subjects:
- kind: ServiceAccount
  name: kyverno-cleanup-controller
  namespace: kyverno