apiVersion: v1
kind: Pod
metadata:
  name: dangerous-capabilities-pod
  namespace: default
spec:
  containers:
  - name: tools
    image: tools:latest
    securityContext:
      capabilities:
        add: 
          - NET_ADMIN     # Dangerous capability (CIS 4.2.7)
          - SYS_ADMIN     # Very dangerous capability that provides extensive privileges
      runAsUser: 0        # Running as root (security best practice violation)