apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-4-4-2-external-secret-storage
  annotations:
    policies.kyverno.io/category: CIS 4.4.2
    policies.kyverno.io/description: |
      Checks for usage of external secret storage annotation or label in Secret or Namespace if available.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-external-secret-storage
      match:
        any:
        - resources:
            kinds:
              - Secret
              - Namespace
      validate:
        message: "External secret storage should be used (look for external-secrets.io annotation or label)."
        anyPattern:
          - metadata:
              annotations:
                external-secrets.io/provider: "?*"
          - metadata:
              labels:
                external-secrets.io/provider: "?*" 