apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: supported-4.1.2
  annotations:
    policies.kyverno.io/title: Minimize access to secrets
    policies.kyverno.io/category: RBAC
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Role, ClusterRole
    policies.kyverno.io/description: Validates minimal access to secrets for least
      privilege. Checks roles granting get, list, or watch permissions on secrets (CIS 4.1.2).
    policies.kyverno.io/cel: 'true'
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: restrict-secrets-access
    match:
      any:
      - resources:
          kinds:
          - Role
          - ClusterRole
    validate:
      message: Access to secrets should be minimized.
      cel:
        expressions:
        - expression: >-
            object.rules.all(rule,
              !(rule.resources.exists(r, r == 'secrets') &&
                (rule.verbs.exists(v, v == 'get') ||
                 rule.verbs.exists(v, v == 'list') ||
                 rule.verbs.exists(v, v == 'watch') ||
                 rule.verbs.exists(v, v == '*')))
            )
          message: Access to secrets should be minimized.
