apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: supported-4.2.1
  annotations:
    policies.kyverno.io/title: Minimize privileged containers
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Ensure that privileged containers are not allowed.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: restrict-privileged
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: "Privileged containers are not allowed."
        pattern:
          spec:
            containers:
              - securityContext:
                  privileged: false 