apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3-2-9-rotate-kubelet-server-certificate
  annotations:
    policies.kyverno.io/category: CIS 3.2.9
    policies.kyverno.io/description: |
      Checks for RotateKubeletServerCertificate flag set to true in node annotations or ConfigMap if available.
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: check-rotate-kubelet-server-certificate
      match:
        any:
        - resources:
            kinds:
              - Node
      validate:
        message: "RotateKubeletServerCertificate should be true."
        pattern:
          metadata:
            annotations:
              kubelet.config.RotateKubeletServerCertificate: "true" 