apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3-2-3-client-ca-file
  annotations:
    policies.kyverno.io/category: CIS 3.2.3
    policies.kyverno.io/description: |
      Checks for clientCAFile configuration in node annotations or ConfigMap if available.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-client-ca-file
      match:
        any:
        - resources:
            kinds:
              - Node
      validate:
        message: "clientCAFile should be configured."
        pattern:
          metadata:
            annotations:
              kubelet.config.clientCAFile: "?*" 