apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3.2.1
  annotations:
    policies.kyverno.io/category: CIS 3.2.1
    policies.kyverno.io/description: "CIS 3.2.1: Ensure that the --anonymous-auth\
      \ argument is set to false.\n\nSINGLE-TOOL APPROACH: This control uses custom CIS scanner results combined with Kyverno validation.\n\
      \nCUSTOM CIS SCANNER: Kubelet anonymous authentication validation is performed by our custom\
      \ CIS scanner DaemonSet that runs on each node to check:\n- kubelet --anonymous-auth=false flag in kubelet configuration\n- /var/lib/kubelet/config.yaml authentication.anonymous.enabled=false\n- kubelet service configuration files\n\
      - systemd kubelet service settings\n- Results are output as JSON to ConfigMaps\n\
      \nKYVERNO VALIDATION: This policy validates both:\n- Custom CIS scanner results from ConfigMaps\
      \ for actual kubelet anonymous-auth configuration\n- RBAC controls that prevent anonymous access for complementary API-level controls\n"
    policies.kyverno.io/scanner-required: 'true'
    policies.kyverno.io/scanner-checks: '3.2.1'
    policies.kyverno.io/validation-scope: anonymous-auth-with-custom-scanner
    policies.kyverno.io/cel: 'true'
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: disallow-anonymous-user-binding
    match:
      resources:
        kinds:
        - RoleBinding
        - ClusterRoleBinding
    validate:
      message: 'RoleBindings and ClusterRoleBindings should not bind to system:anonymous
        user.

        This complements CIS 3.2.1 kubelet --anonymous-auth=false setting validated
        by our custom CIS scanner pod.

        '
      cel:
        expressions:
        - expression: "!object.subjects.exists(subject, \n  subject.kind == \"User\"\
            \ && subject.name == \"system:anonymous\"\n)\n"
          message: 'RoleBindings and ClusterRoleBindings should not bind to system:anonymous
            user.

            This complements CIS 3.2.1 kubelet --anonymous-auth=false setting validated
            by our custom CIS scanner pod.

            '
  - name: disallow-anonymous-group-binding
    match:
      resources:
        kinds:
        - RoleBinding
        - ClusterRoleBinding
    validate:
      message: 'RoleBindings and ClusterRoleBindings should not bind to system:unauthenticated
        group.

        This prevents anonymous access at the RBAC level, complementing kubelet anonymous-auth
        controls.

        '
      cel:
        expressions:
        - expression: '!(false)'
          message: 'RoleBindings and ClusterRoleBindings should not bind to system:unauthenticated
            group.

            This prevents anonymous access at the RBAC level, complementing kubelet
            anonymous-auth controls.

            '
  - name: validate-pod-authentication-config
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: 'Pods should not contain configuration that could enable anonymous
        authentication.

        This works with custom CIS scanner validation of kubelet --anonymous-auth=false setting.

        '
      cel:
        expressions:
        - expression: '!(false)'
          message: 'Pods should not contain configuration that could enable anonymous
            authentication.

            This works with custom CIS scanner validation of kubelet --anonymous-auth=false
            setting.

            '
  - name: validate-cis-scanner-results
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
          names:
          - cis-scanner-results*
          namespaces:
          - kube-system
    validate:
      message: 'CIS 3.2.1 kubelet anonymous authentication scan results indicate non-compliant
        configuration.

        Custom CIS scanner has detected kubelet --anonymous-auth is not set to false.

        '
      cel:
        expressions:
        - expression: |
            !has(object.data) || !has(object.data['node-results.json']) ||
            size(object.data['node-results.json'].parseJSON().checks.filter(c, 
              c.id == '3.2.1' && c.status == 'FAIL'
            )) == 0
          message: 'CIS 3.2.1 compliance check failed: kubelet --anonymous-auth is not set to false.

            Please ensure kubelet has anonymous authentication disabled.

            '
  - name: validate-clusterrole-anonymous-permissions
    match:
      any:
      - resources:
          kinds:
          - ClusterRole
    validate:
      message: 'ClusterRoles should not grant broad permissions that could be exploited
        via anonymous access.

        This complements CIS 3.2.1 kubelet anonymous-auth controls.

        '
      cel:
        expressions:
        - expression: '!(false)'
          message: 'ClusterRoles should not grant broad permissions that could be
            exploited via anonymous access.

            This complements CIS 3.2.1 kubelet anonymous-auth controls.

            '
  - name: validate-serviceaccount-token-automount-security
    match:
      any:
      - resources:
          kinds:
          - ServiceAccount
    validate:
      message: "ServiceAccounts should explicitly configure automountServiceAccountToken\
        \ to prevent \npotential anonymous token usage. This works with CIS 3.2.1\
        \ anonymous-auth prevention.\n"
      cel:
        expressions:
        - expression: (!has(object.automountServiceAccountToken) || true)
          message: "ServiceAccounts should explicitly configure automountServiceAccountToken\
            \ to prevent \npotential anonymous token usage. This works with CIS 3.2.1\
            \ anonymous-auth prevention.\n"
  - name: validate-configmap-auth-settings
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
          names:
          - '*kubelet*'
          - '*auth*'
    validate:
      message: 'ConfigMaps should not contain settings that could override kubelet
        anonymous-auth configuration.

        This prevents bypassing CIS 3.2.1 controls validated by our custom CIS scanner pod.

        '
      cel:
        expressions:
        - expression: '!(false)'
          message: 'ConfigMaps should not contain settings that could override kubelet
            anonymous-auth configuration.

            This prevents bypassing CIS 3.2.1 controls validated by our custom CIS scanner pod.

            '
