apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3-2-5-streaming-connection-idle-timeout
  annotations:
    policies.kyverno.io/category: CIS 3.2.5
    policies.kyverno.io/description: |
      CIS 3.2.5: Ensure that the --streaming-connection-idle-timeout argument is not set to 0.
      
      IMPORTANT: This control requires direct access to worker node kubelet configuration files 
      to validate the streaming connection idle timeout setting. Kyverno cannot directly access node configuration files.
      
      KUBE-BENCH INTEGRATION REQUIRED: This control must be validated using kube-bench, which runs 
      privileged pods on worker nodes to access and validate kubelet configuration files.
      
      This policy validates Pod-level resource limits and timeout configurations that relate to connection management, 
      but the primary validation of kubelet streaming connection settings occurs through kube-bench.
    policies.kyverno.io/kube-bench-required: "true"
    policies.kyverno.io/validation-scope: "limited-pod-resource-security"
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-pod-resource-limits
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: |
          Pods should have appropriate resource limits and timeout configurations.
          Note: Actual kubelet streaming connection timeout validation requires kube-bench.
        pattern:
          spec:
            =(containers):
            - =(resources):
                =(limits):
                  =(cpu): "?*"
                  =(memory): "?*"
                =(requests):
                  =(cpu): "?*"
                  =(memory): "?*"