apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3.2.7
  annotations:
    policies.kyverno.io/category: CIS 3.2.7
    policies.kyverno.io/description: "CIS 3.2.7: Ensure that the --protect-kernel-defaults\
      \ argument is set to true.\n\nIMPORTANT: This control requires direct access\
      \ to worker node kubelet configuration files \nto validate the protect kernel\
      \ defaults setting. Kyverno cannot directly access node configuration files.\n\
      \nSINGLE-TOOL APPROACH: This control uses custom CIS scanner results combined with Kyverno validation.\n\
      \nCUSTOM CIS SCANNER: Kubelet protect kernel defaults validation is performed by our custom\
      \ CIS scanner DaemonSet that runs on each node to check:\n- kubelet --protect-kernel-defaults flag in kubelet configuration\n- /var/lib/kubelet/config.yaml kernel protection settings\n- kubelet service configuration files\n\
      - Results are output as JSON to ConfigMaps\n\
      \nKYVERNO VALIDATION: This policy validates both:\n- Custom CIS scanner results from ConfigMaps\
      \ for actual kubelet kernel defaults protection configuration\n- Pod-level kernel and system security configurations that relate to kernel protection\n"
    policies.kyverno.io/scanner-required: 'true'
    policies.kyverno.io/scanner-checks: '3.2.7'
    policies.kyverno.io/validation-scope: protect-kernel-defaults-with-custom-scanner
    policies.kyverno.io/cel: 'true'
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: validate-pod-kernel-security
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: 'Pods should not access kernel-level features or privileged system
        resources.

        Note: Actual kubelet kernel defaults protection validation requires our custom CIS scanner pod.

        '
      cel:
        expressions:
        - expression: (!has(object.spec.securityContext) || (!has(object.spec.securityContext.runAsNonRoot)
            || true)) && (!has(object.spec.containers) || true)
          message: 'Pods should not access kernel-level features or privileged system
            resources.

            Note: Actual kubelet kernel defaults protection validation (CIS 3.2.7) is handled by
            our custom CIS scanner pod.

            '
  - name: validate-cis-scanner-results
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
          names:
          - cis-scanner-results*
          namespaces:
          - kube-system
    validate:
      message: 'CIS 3.2.7 kubelet protect kernel defaults scan results indicate non-compliant
        configuration.

        Custom CIS scanner has detected kubelet --protect-kernel-defaults is not set to true.

        '
      cel:
        expressions:
        - expression: |
            !has(object.data) || !has(object.data['node-results.json']) ||
            size(object.data['node-results.json'].parseJSON().checks.filter(c, 
              c.id == '3.2.7' && c.status == 'FAIL'
            )) == 0
          message: 'CIS 3.2.7 compliance check failed: kubelet --protect-kernel-defaults is not set to true.

            Please ensure kubelet has proper kernel defaults protection configuration.

            '
