apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3-1-3-kubelet-config-permissions
  annotations:
    policies.kyverno.io/category: CIS 3.1.3
    policies.kyverno.io/description: |
      Checks for kubelet config file permissions in node annotations or ConfigMap if available.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-kubelet-config-permissions
      match:
        any:
        - resources:
            kinds:
              - Node
      validate:
        message: "kubelet config file permissions should be 644 or more restrictive."
        pattern:
          metadata:
            annotations:
              kubelet.config.permissions: "0644" 