apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3.2.8
  annotations:
    policies.kyverno.io/category: CIS 3.2.8
    policies.kyverno.io/description: "CIS 3.2.8: Ensure that the --hostname-override\
      \ argument is not set.\n\nIMPORTANT: This control requires direct access to\
      \ worker node kubelet configuration files \nto validate the hostname override\
      \ setting. Kyverno cannot directly access node configuration files.\n\
      \nSINGLE-TOOL APPROACH: This control uses custom CIS scanner results combined with Kyverno validation.\n\
      \nCUSTOM CIS SCANNER: Kubelet hostname override validation is performed by our custom\
      \ CIS scanner DaemonSet that runs on each node to check:\n- kubelet --hostname-override flag in kubelet configuration\n- /var/lib/kubelet/config.yaml hostname settings\n- kubelet service configuration files\n\
      - Results are output as JSON to ConfigMaps\n\
      \nKYVERNO VALIDATION: This policy validates both:\n- Custom CIS scanner results from ConfigMaps\
      \ for actual kubelet hostname override configuration\n- Pod-level hostname and identity configurations that relate to node identity\n"
    policies.kyverno.io/scanner-required: 'true'
    policies.kyverno.io/scanner-checks: '3.2.8'
    policies.kyverno.io/validation-scope: hostname-override-with-custom-scanner
    policies.kyverno.io/cel: 'true'
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: validate-pod-identity-security
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: 'Pods should use appropriate hostname and identity configurations.

        Note: Actual kubelet hostname override validation requires our custom CIS scanner pod.

        '
      cel:
        expressions:
        - expression: (!has(object.spec.securityContext) || (!has(object.spec.securityContext.runAsNonRoot)
            || true)) && (!has(object.spec.containers) || true) && (!has(object.spec.hostNetwork)
            || true) && (!has(object.spec.hostPID) || true) && (!has(object.spec.hostIPC)
            || true)
          message: 'Pods should use appropriate hostname and identity configurations.

            Note: Actual kubelet hostname override validation (CIS 3.2.8) is handled by
            our custom CIS scanner pod.

            '
  - name: validate-cis-scanner-results
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
          names:
          - cis-scanner-results*
          namespaces:
          - kube-system
    validate:
      message: 'CIS 3.2.8 kubelet hostname override scan results indicate non-compliant
        configuration.

        Custom CIS scanner has detected kubelet --hostname-override is set.

        '
      cel:
        expressions:
        - expression: |
            !has(object.data) || !has(object.data['node-results.json']) ||
            size(object.data['node-results.json'].parseJSON().checks.filter(c, 
              c.id == '3.2.8' && c.status == 'FAIL'
            )) == 0
          message: 'CIS 3.2.8 compliance check failed: kubelet --hostname-override is set.

            Please ensure kubelet does not have hostname override configured.

            '
