apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3-2-6-make-iptables-util-chains
  annotations:
    policies.kyverno.io/category: CIS 3.2.6
    policies.kyverno.io/description: |
      Checks for make-iptables-util-chains set to true in node annotations or ConfigMap if available.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-make-iptables-util-chains
      match:
        any:
        - resources:
            kinds:
              - Node
      validate:
        message: "make-iptables-util-chains should be set to true."
        pattern:
          metadata:
            annotations:
              kubelet.config.makeIPTablesUtilChains: "true" 