apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3-2-5-streaming-connection-idle-timeout
  annotations:
    policies.kyverno.io/category: CIS 3.2.5
    policies.kyverno.io/description: |
      Checks for streaming-connection-idle-timeout not set to 0 in node annotations or ConfigMap if available.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-streaming-connection-idle-timeout
      match:
        any:
        - resources:
            kinds:
              - Node
      validate:
        message: "streaming-connection-idle-timeout should not be set to 0."
        pattern:
          metadata:
            annotations:
              kubelet.config.streamingConnectionIdleTimeout: "!0" 