apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3-1-4-kubelet-config-owner
  annotations:
    policies.kyverno.io/category: CIS 3.1.4
    policies.kyverno.io/description: |
      CIS 3.1.4: Ensure that the kubelet configuration file ownership is set to root:root.
      
      IMPORTANT: This control requires direct access to worker node file systems to validate kubelet 
      configuration file ownership. Kyverno cannot directly access node file systems or validate file ownership.
      
      KUBE-BENCH INTEGRATION REQUIRED: This control must be validated using kube-bench, which runs 
      privileged pods on worker nodes to access and validate file ownership on kubelet configuration files.
      
      This policy validates Pod security contexts and ownership-related configurations, but the primary 
      validation of actual file ownership occurs through kube-bench node-level scanning.
    policies.kyverno.io/kube-bench-required: "true"
    policies.kyverno.io/validation-scope: "limited-pod-security-context"
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-pod-ownership-security
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: |
          Pods should use appropriate ownership and security contexts.
          Note: Actual kubelet config file ownership validation requires kube-bench.
        pattern:
          spec:
            =(securityContext):
              =(runAsNonRoot): "true"
              =(runAsUser): ">0"
              =(runAsGroup): ">0"
              =(fsGroup): ">0"