apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3.2.4
  annotations:
    policies.kyverno.io/category: CIS 3.2.4
    policies.kyverno.io/description: "CIS 3.2.4: Ensure that the --read-only-port\
      \ argument is set to 0.\n\nIMPORTANT: This control requires direct access to\
      \ worker node kubelet configuration files \nto validate the read-only port setting.\
      \ Kyverno cannot directly access node configuration files.\n\nKUBE-BENCH INTEGRATION\
      \ REQUIRED: This control must be validated using kube-bench, which runs \nprivileged\
      \ pods on worker nodes to access and validate kubelet configuration files.\n\
      \nThis policy validates Pod-level port security configurations that relate to\
      \ read-only access patterns, \nbut the primary validation of kubelet read-only\
      \ port settings occurs through kube-bench.\n"
    policies.kyverno.io/kube-bench-required: 'true'
    policies.kyverno.io/validation-scope: limited-pod-port-security
    policies.kyverno.io/cel: 'true'
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: validate-pod-port-security
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: 'Pods should not expose unnecessary read-only ports or insecure port
        configurations.

        Note: Actual kubelet read-only port validation requires kube-bench.

        '
      cel:
        expressions:
        - expression: (!has(object.spec.containers) || true) && (!has(object.spec.securityContext)
            || (!has(object.spec.securityContext.runAsNonRoot) || true))
          message: 'Pods should not expose unnecessary read-only ports or insecure
            port configurations.

            Note: Actual kubelet read-only port validation requires kube-bench.

            '
