apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3-1-3-kubelet-config-permissions
  annotations:
    policies.kyverno.io/category: CIS 3.1.3
    policies.kyverno.io/description: |
      CIS 3.1.3: Ensure that the kubelet configuration file has permissions of 644 or more restrictive.
      
      IMPORTANT: This control requires direct access to worker node file systems to validate kubelet 
      configuration file permissions. Kyverno cannot directly access node file systems or validate file permissions.
      
      KUBE-BENCH INTEGRATION REQUIRED: This control must be validated using kube-bench, which runs 
      privileged pods on worker nodes to access and validate file permissions on kubelet configuration files.
      
      This policy validates Pod security contexts and configuration management practices, but the primary 
      validation of actual file permissions occurs through kube-bench node-level scanning.
    policies.kyverno.io/kube-bench-required: "true"
    policies.kyverno.io/validation-scope: "limited-pod-security-context"
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-config-volume-security
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: |
          Pods accessing configuration files should use secure volume mounts and contexts.
          Note: Actual kubelet config file permission validation requires kube-bench.
        pattern:
          spec:
            =(volumes):
            - =(configMap):
                =(defaultMode): "<=0644"
            =(securityContext):
              =(runAsNonRoot): "true"
              =(fsGroup): ">0"