apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-3-2-4-read-only-port
  annotations:
    policies.kyverno.io/category: CIS 3.2.4
    policies.kyverno.io/description: |
      Checks for readOnlyPort: 0 in node annotations or ConfigMap if available.
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: check-read-only-port
      match:
        any:
        - resources:
            kinds:
              - Node
      validate:
        message: "readOnlyPort should be set to 0."
        pattern:
          metadata:
            annotations:
              kubelet.config.readOnlyPort: "0" 