apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: cis-5-3-2-secrets-management
spec:
  rules:
    - name: external-secrets-management
      assert:
        all:
          - message: "External secrets management should be configured (AWS Secrets Manager integration)."
            check:
              (length(planned_values.root_module.resources[?type=='aws_secretsmanager_secret']) > `0` || length(planned_values.root_module.resources[?type=='aws_eks_addon' && contains(values.addon_name, 'aws-secrets-store-csi-driver')]) > `0`): true
          - message: "Secrets should be encrypted with customer-managed KMS keys."
            check:
              (length(planned_values.root_module.resources[?type=='aws_secretsmanager_secret' && values.kms_key_id]) > `0` || length(planned_values.root_module.resources[?type=='aws_kms_key']) > `0`): true