# CIS Control: 3.1.1
# Description: kubeconfig file permissions set to 644 or more restrictive
# Not enforceable by Kyverno; requires checking file permissions on nodes, which must be audited manually or via infrastructure as code (e.g., Terraform, Ansible).

apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: cis-3.1.1-kubeconfig-file-permissions-set-to-644-or-more-restrictive
  annotations:
    cis.kubernetes.io/id: "3.1.1"
    cis.kubernetes.io/description: "kubeconfig file permissions set to 644 or more restrictive"
spec:
  background: false
  rules: []