# This is a stub Kyverno policy for CIS 4.3.2: Ensure all Namespaces have Network Policies
# Replace this stub with the official Kyverno policy when available
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-4.3.2-ensure-all-namespaces-have-network-policies
  annotations:
    cis.kubernetes.io/id: "4.3.2"
    description: "Ensure all namespaces have network policies (by requiring a label)"
spec:
  validationFailureAction: Audit # Change to 'enforce' to block
  background: true
  rules:
    - name: require-ns-networkpolicy-label
      match:
        any:
        - resources:
            kinds:
              - Namespace
      exclude:
        any:
        # Exclude system namespaces
        - resources:
            namespaces:
              - kube-system
              - kube-public
              - kube-node-lease
              - kyverno # Assuming kyverno runs in its own namespace
      validate:
        message: "Namespace must have a 'network-policy/status=applied' label to indicate NetworkPolicies are configured."
        pattern:
          metadata:
            labels:
              network-policy/status: applied