# CIS Control: 3.2.5
# Description: --streaming-connection-idle-timeout not set to 0
# NOTE: This control is not enforceable via Kyverno policy. Stub only.

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-3.2.5-streaming-connection-idle-timeout-not-set-to-0
  annotations:
    cis.kubernetes.io/id: "3.2.5"
    cis.kubernetes.io/description: "--streaming-connection-idle-timeout not set to 0"
spec:
  rules: []