# This is a stub Kyverno policy for CIS 4.1.6: Mount service account tokens only when necessary
# Replace this stub with the official Kyverno policy when available
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-4.1.6-mount-service-account-tokens-only-when-necessary
  annotations:
    cis.kubernetes.io/id: "4.1.6"
    description: "Mount service account tokens only when necessary"
spec:
  validationFailureAction: Audit # Change to 'enforce' to block
  background: true
  rules:
  - name: restrict-pod-automountServiceAccountToken
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Pod spec.automountServiceAccountToken must be set to false unless explicitly needed."
      # This policy requires pods to explicitly set automountServiceAccountToken: false
      # Alternatively, you could mutate it to false if not set, or validate based on the linked ServiceAccount setting.
      # This simpler validation enforces the explicit setting on the Pod itself.
      pattern:
        spec:
          automountServiceAccountToken: false
  - name: restrict-sa-automountServiceAccountToken
    match:
      any:
      - resources:
          kinds:
          - ServiceAccount
    validate:
      message: "ServiceAccounts should set automountServiceAccountToken to false by default."
      # This requires ServiceAccounts to explicitly set automountServiceAccountToken: false
      pattern:
        automountServiceAccountToken: false