# CIS Control: 4.5.1
# Description: Use namespaces for resource boundaries
# NOTE: This control is not enforceable via Kyverno policy. Stub only.

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-4.5.1-use-namespaces-for-resource-boundaries
  annotations:
    cis.kubernetes.io/id: "4.5.1"
    cis.kubernetes.io/description: "Use namespaces for resource boundaries"
spec:
  rules: []