# This is a stub Kyverno policy for CIS 4.2.1: Minimize privileged containers
# Replace this stub with the official Kyverno policy when available
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-4.2.1-minimize-privileged-containers
  annotations:
    cis.kubernetes.io/id: "4.2.1"
    description: "Minimize privileged containers"
spec:
  validationFailureAction: Audit # Change to 'enforce' to block
  background: true
  rules:
    - name: privileged-containers
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Privileged containers are disallowed. The field
          spec.containers[*].securityContext.privileged must be unset or set to `false`.
        pattern:
          spec:
            =(initContainers):
              - =(securityContext):
                  =(privileged): "false"
            containers:
              - =(securityContext):
                  =(privileged): "false"
            =(ephemeralContainers):
              - =(securityContext):
                  =(privileged): "false"