apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-2-1-1-enable-audit-logs
  annotations:
    policies.kyverno.io/category: CIS 2.1.1
    policies.kyverno.io/description: |
      Checks for audit logging configuration in ConfigMap or node annotations if available.
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: check-audit-logging
      match:
        any:
        - resources:
            kinds:
              - ConfigMap
      validate:
        message: "Audit logging should be enabled (look for 'audit' in data.logging)."
        pattern:
          data:
            logging: "?*audit?*"

    - name: validate-auditsink
      match:
        any:
        - resources:
            kinds:
              - AuditSink
      validate:
        message: "AuditSink must be properly configured with webhook endpoint and appropriate policy level."
        pattern:
          spec:
            webhook:
              throttle:
                qps: ">0"
                burst: ">0"
              clientConfig:
                url: "?*"
            policy:
              level: "Metadata | Request | RequestResponse"
              stages:
                - "ResponseComplete"

    - name: validate-eks-audit-logging
      match:
        any:
        - resources:
            kinds:
              - ConfigMap
            names:
              - eks-cluster-config
            namespaces:
              - kyverno-aws
      validate:
        message: "EKS control plane logging must be enabled for audit logs."
        pattern:
          data:
            logging: "*audit*"

    - name: validate-terraform-audit-logging
      match:
        any:
        - resources:
            kinds:
              - json.kyverno.io/v1alpha1
      validate:
        message: "Terraform configuration must enable EKS audit logging."
        pattern:
          resource_changes:
            - type: "aws_eks_cluster"
              change:
                after:
                  enabled_cluster_log_types:
                    - "audit" 