apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: application-ns
  name: app-reader
rules:
# Avoiding wildcard use in apiGroups (CIS 4.1.3)
- apiGroups: [""]  # Core API group
  # Not including secrets in resources (CIS 4.1.2)
  # Not including pods in resources with create verb (CIS 4.1.4)
  resources: ["services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  # Only read operations, no create (CIS 4.1.4)
  verbs: ["get", "list", "watch"]
# Using specific API groups, not wildcards (CIS 4.1.3)
- apiGroups: ["apps"]  # Specific API group instead of using extensions
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
# No bind, impersonate or escalate verbs used (CIS 4.1.8)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-reader-binding
  namespace: application-ns
subjects:
- kind: ServiceAccount
  name: app-service-account
  namespace: application-ns
roleRef:
  kind: Role
  name: app-reader
  apiGroup: rbac.authorization.k8s.io