apiVersion: v1
kind: Namespace
metadata:
  name: application-ns
  labels:
    name: application-ns
    environment: production
    # Adding Pod Security Standards labels (CIS 5.1.1)
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: application-ns
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-specific-ingress
  namespace: application-ns
spec:
  podSelector:
    matchLabels:
      app: secure-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: frontend-ns
    ports:
    - protocol: TCP
      port: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: application-ns
  # Adding IRSA annotation for EKS (CIS 5.2.1)
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/app-role"