apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: cis-4-1-2-minimize-secrets-access
spec:
  rules:
    - name: restrict-secrets-access-iam
      assert:
        all:
          - message: "IAM policies should not grant broad access to secrets management services."
            check:
              "(length(planned_values.root_module.resources[?type=='aws_iam_role_policy_attachment' && (contains(values.policy_arn, 'SecretsManagerFullAccess') || contains(values.policy_arn, 'ParameterStoreFullAccess'))]) == `0`)": true
          - message: "IAM roles should have minimal secrets access for EKS operations."
            check:
              "(length(planned_values.root_module.resources[?type=='aws_iam_role_policy' && (contains(values.policy, '\"secretsmanager:*\"') || contains(values.policy, '\"Action\":\"*\"'))]) == `0`)": true