apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: cis-4-1-1-minimize-cluster-admin
spec:
  rules:
    - name: restrict-cluster-admin-iam-roles
      assert:
        all:
          - message: "IAM roles should not have overly broad permissions equivalent to cluster-admin."
            check:
              (length(planned_values.root_module.resources[?type=='aws_iam_role_policy_attachment' && contains(values.policy_arn, 'AdministratorAccess')]) == `0`): true
          - message: "IAM policies should follow principle of least privilege for EKS access."
            check:
              (length(planned_values.root_module.resources[?type=='aws_iam_role' && contains(values.name, 'eks')]) > `0`): true