apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: cis-4-1-8-restrict-bind-impersonate-escalate
spec:
  rules:
    - name: no-privilege-escalation-iam
      assert:
        all:
          - message: "IAM policies should not allow privilege escalation through sts:AssumeRole on wildcard resources."
            check:
              (length(planned_values.root_module.resources[?type=='aws_iam_role_policy' && contains(values.policy, 'sts:AssumeRole') && contains(values.policy, '"Resource": "*"')]) == `0`): true
          - message: "IAM roles should not have iam:PassRole permissions on wildcard resources."
            check:
              (length(planned_values.root_module.resources[?type=='aws_iam_role_policy' && contains(values.policy, 'iam:PassRole') && contains(values.policy, '"Resource": "*"')]) == `0`): true