# kyverno-policies/cis/cis-4.3.2.yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-4.3.2-require-namespace-networkpolicy
  annotations:
    policies.kyverno.io/title: Require NetworkPolicy in Namespaces
    policies.kyverno.io/category: CIS EKS Benchmarks
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Namespace, NetworkPolicy
    policies.kyverno.io/minversion: 1.6.0 # Requires apiCall context
    policies.kyverno.io/description: >-
      Network segmentation should be enforced using NetworkPolicies. This policy validates
      that every Namespace (excluding system namespaces) contains at least one NetworkPolicy resource.
    policies.kyverno.io/benchmark: cis-eks
    policies.kyverno.io/controls: "4.3.2"
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-namespace-networkpolicy
      match:
        any:
        - resources:
            kinds:
              - Namespace
      exclude:
        any:
        # Exclude system and Kyverno namespaces
        - resources:
            namespaces:
            - kube-system
            - kube-public
            - kube-node-lease
            - kyverno
      context:
        - name: networkpolicies_in_namespace
          apiCall:
            # Use the namespace name from the matched Namespace resource
            urlPath: "/apis/networking.k8s.io/v1/namespaces/{{request.object.metadata.name}}/networkpolicies"
            jmesPath: "items[]" # Get the list of NetworkPolicy items
      validate:
        message: "Namespace must have at least one NetworkPolicy defined (CIS 4.3.2)."
        deny:
          conditions:
            all:
            - key: "{{ networkpolicies_in_namespace }}"
              operator: Equals
              value: [] # Deny (fail validation) if the list of NetworkPolicies is empty