apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5.3.2-require-networkpolicy
  annotations:
    policies.kyverno.io/title: Require NetworkPolicy
    policies.kyverno.io/category: CIS EKS Benchmark Section 5.3
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Namespace, NetworkPolicy
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kyverno-version: 1.7.1
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      NetworkPolicies are crucial for controlling traffic flow between Pods and Namespaces.
      By default, traffic is unrestricted. Defining NetworkPolicies helps implement network segmentation
      and limit the blast radius in case of a compromise. This policy requires that every Namespace
      (excluding system namespaces) has at least one NetworkPolicy defined.
      CIS Benchmark Control: 5.3.2 Ensure that all Namespaces have NetworkPolicies defined
    policies.kyverno.io/cis_controls: "5.3.2"
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-for-networkpolicy
      match:
        any:
        - resources:
            kinds:
              - Namespace
      exclude:
        any:
        - resources:
            # Exclude system and Kyverno namespaces
            names:
              - kube-system
              - kube-public
              - kube-node-lease
              - kyverno
              - gatekeeper-system # Add other system/management namespaces if necessary
      context:
        # Check if any NetworkPolicy exists in the Namespace being admitted/checked
        - name: networkpolicycount
          apiCall:
            urlPath: "/apis/networking.k8s.io/v1/namespaces/{{request.object.metadata.name}}/networkpolicies"
            jmesPath: "items | length(@)"
      validate:
        message: "Namespace requires at least one NetworkPolicy. CIS 5.3.2"
        deny:
          conditions:
            all:
            # Deny if the count of NetworkPolicies is 0
            - key: "{{ networkpolicycount }}"
              operator: Equals
              value: 0