#!/bin/bash
set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

COMPLIANT_DIR="terraform/compliant"
POLICY_DIR="policies/kubernetes"
REPORT_DIR="reports/compliance"
TFPLAN_JSON="$COMPLIANT_DIR/tfplan.json"
KYVERNO_REPORT="$REPORT_DIR/kyverno-tfplan-report.yaml"
SUMMARY_REPORT="$REPORT_DIR/compliant-summary.md"

mkdir -p "$REPORT_DIR"

TOTAL_POLICIES=$(find "$POLICY_DIR" -name "*.yaml" -type f | wc -l | tr -d ' ')
echo -e "${BLUE}📊 Found $TOTAL_POLICIES policies to validate${NC}"

echo -e "${YELLOW}⚙️  [25%] Initializing Terraform...${NC}"
terraform -chdir="$COMPLIANT_DIR" init -input=false -no-color > /dev/null

echo -e "${YELLOW}🚀 [50%] Applying compliant configuration...${NC}"
terraform -chdir="$COMPLIANT_DIR" apply -auto-approve -input=false -no-color

echo -e "${YELLOW}📄 [75%] Generating Terraform plan JSON...${NC}"
terraform -chdir="$COMPLIANT_DIR" show -json > "$TFPLAN_JSON"

if ! command -v kyverno &> /dev/null; then
  echo "❌ [ERROR] Kyverno CLI not found in PATH. Please install Kyverno CLI."
  exit 1
fi

echo -e "${YELLOW}🔍 [90%] Running Kyverno policy validation...${NC}"
START_TIME=$(date +%s.%N)
kyverno apply "$POLICY_DIR"/*.yaml --resource "$TFPLAN_JSON" --output yaml > "$KYVERNO_REPORT"
END_TIME=$(date +%s.%N)
DURATION=$(awk "BEGIN {printf \"%.3f\", $END_TIME - $START_TIME}")

cat > "$SUMMARY_REPORT" << EOF
# 📊 Compliant Configuration Validation Summary

**Generated**: $(date)
**Duration**: ${DURATION}s

## 📈 Statistics

| Metric | Value |
|--------|-------|
| **Total Policies** | $TOTAL_POLICIES |
| **Validation Duration** | ${DURATION}s |
| **Configuration Type** | Compliant |
| **Status** | ✅ Complete |

## 📄 Reports Generated

- **Detailed Report**: \`$KYVERNO_REPORT\`
- **Summary Report**: \`$SUMMARY_REPORT\`

---
*🤖 Generated by Enhanced Kyverno Validation Suite*
EOF

echo -e "${GREEN}✅ [100%] Validation complete!${NC}"
echo -e "${BLUE}📊 Validated $TOTAL_POLICIES policies in ${DURATION}s${NC}"
echo -e "${BLUE}📄 Detailed report: $KYVERNO_REPORT${NC}"
echo -e "${BLUE}📊 Summary report: $SUMMARY_REPORT${NC}" 