#!/bin/bash
set -e

REPORT_DIR="reports"
SUMMARY_FILE="$REPORT_DIR/executive-summary.md"
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

cat > "$SUMMARY_FILE" << EOF
# ⚙️ Kyverno CIS EKS Compliance Test Report

**Generated**: $TIMESTAMP

---

## 📊 Test Results Overview

### 📋 Policy Unit Tests
EOF

if [ -f "$REPORT_DIR/policy-tests/summary.md" ]; then
    # Extract summary statistics from Markdown file
    if grep -q "Summary Statistics" "$REPORT_DIR/policy-tests/summary.md"; then
        grep -A 6 "Summary Statistics" "$REPORT_DIR/policy-tests/summary.md" | tail -n +2 >> "$SUMMARY_FILE"
    else
        echo "- ❌ No policy test summary available" >> "$SUMMARY_FILE"
    fi
else
    echo "- ❌ No policy test results found" >> "$SUMMARY_FILE"
fi

cat >> "$SUMMARY_FILE" << EOF

### 🛠️ Terraform Compliance Tests
EOF

if [ -f "$REPORT_DIR/terraform-compliance/compliant-plan-scan.md" ] && [ -f "$REPORT_DIR/terraform-compliance/noncompliant-plan-scan.md" ]; then
    echo "- ✅ Compliant configuration scan: **Completed**" >> "$SUMMARY_FILE"
    echo "- ✅ Non-compliant configuration scan: **Completed**" >> "$SUMMARY_FILE"
    
    # Count violations in non-compliant scan
    VIOLATIONS=$(grep -c "fail" "$REPORT_DIR/terraform-compliance/noncompliant-plan-scan.md" 2>/dev/null || echo "0")
    echo "- 🔴 Policy violations detected in non-compliant config: **$VIOLATIONS**" >> "$SUMMARY_FILE"
else
    echo "- ❌ No terraform compliance results found" >> "$SUMMARY_FILE"
fi

cat >> "$SUMMARY_FILE" << EOF

---

## 📝 Report Files

### 📊 Policy Tests
- **Detailed results**: [🗾 detailed-results.md](policy-tests/detailed-results.md)
- **Summary**: [📈 summary.md](policy-tests/summary.md)

### 🛠️ Terraform Compliance
- **Compliant scan**: [✅ compliant-plan-scan.md](terraform-compliance/compliant-plan-scan.md)
- **Non-compliant scan**: [❌ noncompliant-plan-scan.md](terraform-compliance/noncompliant-plan-scan.md)

---

## 📊 Quick Stats

| Test Type | Status | Details |
|-----------|--------|----------|
| Policy Unit Tests | $( [ -f "$REPORT_DIR/policy-tests/summary.md" ] && echo "✅ Complete" || echo "❌ Missing" ) | Individual policy validation |
| Terraform Compliance | $( [ -f "$REPORT_DIR/terraform-compliance/compliant-plan-scan.md" ] && echo "✅ Complete" || echo "❌ Missing" ) | Infrastructure compliance |

---

*🤖 Generated by Kyverno CIS EKS Compliance Test Suite*
EOF

echo "Executive summary generated: $SUMMARY_FILE"