#!/bin/bash
set -e

REPORT_DIR="reports/policy-tests"
RESULTS_FILE="$REPORT_DIR/detailed-results.md"
SUMMARY_FILE="$REPORT_DIR/summary.md"

mkdir -p "$REPORT_DIR"
rm -f "$RESULTS_FILE" "$SUMMARY_FILE"

# Initialize Markdown files
cat > "$RESULTS_FILE" << 'EOF'
# Kyverno Policy Test Results

Detailed test results for all CIS EKS compliance policies.

---

EOF

cat > "$SUMMARY_FILE" << 'EOF'
# Policy Test Summary

## Test Results

EOF

PASSED=0
FAILED=0
ERRORS=0

TEMP_PASS="/tmp/kyverno_pass_count"
TEMP_FAIL="/tmp/kyverno_fail_count"
TEMP_ERROR="/tmp/kyverno_error_count"
echo "0" > "$TEMP_PASS"
echo "0" > "$TEMP_FAIL"
echo "0" > "$TEMP_ERROR"

while IFS= read -r testfile; do
  echo "\n## Test: \`$testfile\`" >> "$RESULTS_FILE"
  echo "Running test: $testfile"
  
  # Run test with error handling
  set +e
  TEST_OUT=$(kyverno test "$(dirname "$testfile")" 2>&1)
  TEST_EXIT_CODE=$?
  set -e
  
  # Format output for Markdown
  echo "\n\`\`\`" >> "$RESULTS_FILE"
  echo "$TEST_OUT" >> "$RESULTS_FILE"
  echo "\`\`\`" >> "$RESULTS_FILE"
  echo "\n---\n" >> "$RESULTS_FILE"
  
  # Handle test command failures
  if [ $TEST_EXIT_CODE -ne 0 ]; then
    echo "\n❌ **ERROR**: Test command failed with exit code $TEST_EXIT_CODE" >> "$RESULTS_FILE"
    echo "- ❌ \`$testfile\` - **ERROR**" >> "$SUMMARY_FILE"
    echo "$(($(cat "$TEMP_ERROR") + 1))" > "$TEMP_ERROR"
    continue
  fi
  
  if echo "$TEST_OUT" | grep -q '\bPass\b'; then
    echo "$(($(cat "$TEMP_PASS") + 1))" > "$TEMP_PASS"
    echo "- ✅ \`$testfile\` - **PASS**" >> "$SUMMARY_FILE"
  fi
  if echo "$TEST_OUT" | grep -q '\bFail\b'; then
    echo "$(($(cat "$TEMP_FAIL") + 1))" > "$TEMP_FAIL"
    echo "- ❌ \`$testfile\` - **FAIL**" >> "$SUMMARY_FILE"
  fi
  if echo "$TEST_OUT" | grep -q '^Error:'; then
    echo "$(($(cat "$TEMP_ERROR") + 1))" > "$TEMP_ERROR"
    echo "- ❌ \`$testfile\` - **ERROR**" >> "$SUMMARY_FILE"
  fi
done < <(find tests -type f -name 'kyverno-test.yaml' | sort)

PASSED=$(cat "$TEMP_PASS")
FAILED=$(cat "$TEMP_FAIL")
ERRORS=$(cat "$TEMP_ERROR")

rm -f "$TEMP_PASS" "$TEMP_FAIL" "$TEMP_ERROR"

TOTAL=$((PASSED+FAILED+ERRORS))
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

# Add summary to summary file
cat >> "$SUMMARY_FILE" << EOF

## Summary Statistics

| Metric | Count |
|--------|-------|
| **Total Tests** | $TOTAL |
| **✅ Passed** | $PASSED |
| **❌ Failed** | $FAILED |
| **❌ Errors** | $ERRORS |

## Test Completion

- **Timestamp**: $TIMESTAMP
- **Status**: $( [ $((FAILED+ERRORS)) -eq 0 ] && echo "✅ All tests passed" || echo "❌ Some tests failed" )

---

*Generated by Kyverno CIS EKS Compliance Test Suite*
EOF

echo "\nSummary:"
echo "Total test cases: $TOTAL"
echo "Passed: $PASSED"
echo "Failed: $FAILED"
echo "Errors: $ERRORS"
echo "\nSee $RESULTS_FILE and $SUMMARY_FILE for full details."

if [ $FAILED -gt 0 ] || [ $ERRORS -gt 0 ]; then
    echo "\n❌ ERROR: $((FAILED+ERRORS)) test(s) failed!"
    exit 1
fi

exit 0