apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: cis-eks-kyverno-test
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "kyverno-test=enabled"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "kyverno-test=enabled"
