apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: cis-5-3-1-encrypt-secrets-kms
spec:
  rules:
    - name: eks-secrets-encryption
      assert:
        all:
          - message: "EKS cluster must have encryption_config for secrets (KMS key may be computed at apply time)."
            check:
              (length(planned_values.root_module.resources[?type=='aws_eks_cluster' && values.encryption_config && length(values.encryption_config[?contains(resources, 'secrets')]) > `0`]) > `0`): true 