apiVersion: v1
kind: Namespace
metadata:
  name: sample-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-sa
  namespace: sample-namespace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/sample-irsa-role
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: sample-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
        network-policy/status: applied
    spec:
      serviceAccountName: sample-sa
      containers:
        - name: sample-container
          image: 123456789012.dkr.ecr.us-west-2.amazonaws.com/nginx:1.25
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80