apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5.3.1-kms-secret-encryption-comprehensive
  annotations:
    policies.kyverno.io/title: KMS Encryption for Kubernetes Secrets
    policies.kyverno.io/category: CIS 5.3.1
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Secret, ConfigMap
    policies.kyverno.io/description: |
      Comprehensive implementation of CIS 5.3.1: Encrypt Kubernetes Secrets with KMS CMKs.
      This policy demonstrates how to implement complete coverage through:
      1. Terraform validation of EKS cluster encryption configuration
      2. Runtime validation of secret encryption
      3. KMS key policy validation
spec:
  rules:
    - name: validate-cluster-encryption-config
      match:
        any:
        - resources:
            kinds:
              - ConfigMap
            names:
              - eks-encryption-config
      validate:
        message: "EKS cluster encryption configuration must be present and valid."
        anyPattern:
          - data:
              encryption-enabled: "true"
              kms-key-arn: "?*"
          - metadata:
              annotations:
                aws.eks.encryption/enabled: "true"

    - name: validate-secret-encryption
      match:
        any:
        - resources:
            kinds:
              - Secret
      validate:
        message: "Secrets must be encrypted with KMS."
        pattern:
          metadata:
            annotations:
              kubernetes.io/encryption-provider: "aws-kms"

    - name: validate-encryption-provider
      match:
        any:
        - resources:
            kinds:
              - ConfigMap
            names:
              - encryption-provider-config
            namespaces:
              - kube-system
      validate:
        message: "Encryption provider must be configured to use KMS."
        pattern:
          data:
            encryption-provider.yaml: "?*kms?*"

    - name: check-encrypt-secrets-kms
      match:
        any:
        - resources:
            kinds:
              - Secret
              - Namespace
      validate:
        message: "Secrets should be encrypted with KMS CMKs (look for kms-key annotation or label)."
        anyPattern:
          - metadata:
              annotations:
                kms-key: "?*"
          - metadata:
              labels:
                kms-key: "?*"