apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5.3.1-kms-secret-encryption-comprehensive
  annotations:
    policies.kyverno.io/title: KMS Encryption for Kubernetes Secrets
    policies.kyverno.io/category: CIS 5.3.1
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Secret, ConfigMap
    policies.kyverno.io/description: |
      Comprehensive implementation of CIS 5.3.1: Encrypt Kubernetes Secrets with KMS CMKs.
      This policy validates secret encryption using reliable Kubernetes resources instead of unreliable ConfigMaps.
      Validates actual secret encryption, KMS annotations, and native resources.
spec:
  rules:
    - name: validate-secret-encryption
      match:
        any:
        - resources:
            kinds:
              - Secret
      validate:
        message: "Secrets must be encrypted with KMS and have proper encryption annotations."
        anyPattern:
          - metadata:
              annotations:
                kubernetes.io/encryption-provider: "aws-kms"
          - metadata:
              annotations:
                kms-key: "?*"
          - metadata:
              labels:
                kms-encrypted: "true"

    - name: validate-namespace-encryption-policy
      match:
        any:
        - resources:
            kinds:
              - Namespace
      validate:
        message: "Namespaces should have encryption policy annotations for secrets."
        anyPattern:
          - metadata:
              annotations:
                encryption.k8s.io/policy: "kms"
          - metadata:
              labels:
                encryption-required: "true"
          - metadata:
              annotations:
                secrets.encryption/kms: "enabled"

    - name: validate-service-account-encryption
      match:
        any:
        - resources:
            kinds:
              - ServiceAccount
      validate:
        message: "ServiceAccount tokens should be encrypted with KMS."
        anyPattern:
          - metadata:
              annotations:
                token.encryption/kms: "enabled"
          - metadata:
              labels:
                kms-encrypted: "true"
          - secrets:
            - name: "?*"
              # ServiceAccount should reference encrypted secrets

    - name: check-encrypt-secrets-kms
      match:
        any:
        - resources:
            kinds:
              - Secret
              - Namespace
      validate:
        message: "Secrets should be encrypted with KMS CMKs (look for kms-key annotation or label)."
        anyPattern:
          - metadata:
              annotations:
                kms-key: "?*"
          - metadata:
              labels:
                kms-key: "?*"
          - metadata:
              annotations:
                aws.encryption/kms-key-id: "?*"