apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-5-4-3-private-nodes
  annotations:
    policies.kyverno.io/category: CIS 5.4.3
    policies.kyverno.io/description: |
      Checks for private node annotation or label in Node or Namespace if available.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-private-nodes
      match:
        any:
        - resources:
            kinds:
              - Node
              - Namespace
      validate:
        message: "Nodes should be private (look for private-node annotation or label)."
        anyPattern:
          - metadata:
              annotations:
                private-node: "true"
          - metadata:
              labels:
                private-node: "true" 