apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-5-4-1-restrict-control-plane-endpoint
  annotations:
    policies.kyverno.io/category: CIS 5.4.1
    policies.kyverno.io/description: |
      Validates control plane endpoint restrictions using reliable Kubernetes resources.
      Checks Services, NetworkPolicies, and Namespaces for endpoint restriction indicators.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-restrict-control-plane-endpoint-namespace
      match:
        any:
        - resources:
            kinds:
              - Namespace
      validate:
        message: "Namespace should have control plane endpoint restriction annotation or label."
        anyPattern:
          - metadata:
              annotations:
                endpoint-restriction: "enabled"
          - metadata:
              labels:
                endpoint-restriction: "enabled"
          - metadata:
              annotations:
                networking.k8s.io/control-plane-access: "restricted"

    - name: validate-service-endpoint-restrictions
      match:
        any:
        - resources:
            kinds:
              - Service
            namespaces:
              - kube-system
      validate:
        message: "Control plane services should have endpoint access restrictions."
        anyPattern:
          - metadata:
              annotations:
                service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          - spec:
              type: "ClusterIP"
          - metadata:
              labels:
                access-control: "restricted"

    - name: validate-network-policy-endpoint-restrictions
      match:
        any:
        - resources:
            kinds:
              - NetworkPolicy
            namespaces:
              - kube-system
      validate:
        message: "NetworkPolicies should restrict control plane endpoint access."
        anyPattern:
          - spec:
              policyTypes:
              - "Ingress"
          - metadata:
              annotations:
                policy-purpose: "control-plane-restriction"
          - spec:
              ingress:
              - from:
                - namespaceSelector: {}

    - name: validate-pod-security-context
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - kube-system
      validate:
        message: "Control plane pods should have security restrictions."
        anyPattern:
          - spec:
              securityContext:
                runAsNonRoot: true
          - metadata:
              annotations:
                endpoint-access: "restricted"
          - spec:
              hostNetwork: false