name: Kyverno CIS Validation

on:
  pull_request:
    branches: [ main, master ] # Adjust branch names if needed

jobs:
  kyverno-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3 # Using latest stable version

      - name: Terraform Format Check
        run: terraform fmt --check -recursive
        working-directory: ./terraform

      - name: Terraform Init (Example - Cluster)
        run: terraform init -backend=false
        working-directory: ./terraform/examples/cluster

      - name: Terraform Validate (Example - Compliant)
        run: terraform validate -var-file=compliant.tfvars
        working-directory: ./terraform/examples/cluster

      - name: Terraform Validate (Example - Non-Compliant)
        run: terraform validate -var-file=noncompliant.tfvars
        working-directory: ./terraform/examples/cluster

      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@v0.1.1

      - name: Run Kyverno Tests
        run: kyverno test kyverno-policies/cis/ # Path relative to checkout root

      - name: Run CIS Validation Script
        run: ./scripts/validate-cis.sh noncompliant-resources # Pass directory as argument