name: Kyverno Policy and Plan Compliance Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kyverno-policy-and-plan-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Install Kyverno CLI
        run: |
          curl -L https://github.com/kyverno/kyverno/releases/latest/download/kyverno-cli_linux_x86_64.tar.gz -o kyverno.tar.gz
          tar -xzf kyverno.tar.gz kyverno
          sudo mv kyverno /usr/local/bin/
          kyverno version

      - name: Install kyverno-json
        run: |
          curl -L https://github.com/kyverno/kyverno-json/releases/latest/download/kyverno-json-linux-amd64.tar.gz -o kyverno-json.tar.gz
          tar -xzf kyverno-json.tar.gz kyverno-json
          sudo mv kyverno-json /usr/local/bin/
          kyverno-json version

      - name: Validate Kyverno policies (Kubernetes manifests)
        run: |
          mkdir -p reports/validate
          kyverno validate kyverno-policies/*.yaml | tee reports/validate/validate.txt

      - name: Plan compliant stack and generate tfplan.json
        run: |
          cd terraform/compliant
          terraform init -input=false
          terraform plan -out=tfplan.binary -input=false
          terraform show -json tfplan.binary > tfplan.json

      - name: Plan noncompliant stack and generate tfplan.json
        run: |
          cd terraform/noncompliant
          terraform init -input=false
          terraform plan -out=tfplan.binary -input=false
          terraform show -json tfplan.binary > tfplan.json

      - name: Run Kyverno JSON policies on compliant plan
        run: |
          mkdir -p reports/compliance
          kyverno-json scan --payload terraform/compliant/tfplan.json --policy kyverno-policies/terraform/ > reports/compliance/kyverno-tfplan-report.yaml

      - name: Run Kyverno JSON policies on noncompliant plan
        run: |
          kyverno-json scan --payload terraform/noncompliant/tfplan.json --policy kyverno-policies/terraform/ > reports/compliance/kyverno-tfplan-noncompliant-report.yaml

      - name: Upload all reports
        uses: actions/upload-artifact@v4
        with:
          name: kyverno-policy-and-plan-reports
          path: reports/

      - name: Fail if compliant plan fails or noncompliant plan passes
        run: |
          set -e
          if grep -q 'FAILED' reports/compliance/kyverno-tfplan-report.yaml; then
            echo "Compliant plan failed policy checks!"; exit 1;
          fi
          if ! grep -q 'FAILED' reports/compliance/kyverno-tfplan-noncompliant-report.yaml; then
            echo "Noncompliant plan did not trigger policy failures!"; exit 1;
          fi 